# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Connor Mulqueen's Blog
email: cjmulque@buffalo.edu
name: Connor Mulqueen
description: >- # this means to ignore newlines until "baseurl:"
  A blogging website for Connor Mulqueen. Nerdy stuff.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: http://connormulqueen.github.io.com/blog # the base hostname & protocol for your site, e.g. http://example.com
BASE_PATH: http://connormulqueen.com/blog
repository: ConnorMulqueen/blog
twitter_username:
github_username:  connormulqueen

# Build settings
markdown: kramdown
paginate: 5
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache


#Site Author
author:
  name        : "Connor Mulqueen"
  bio         : "Some guy who liked Halo enough to become a Software Engineer."
  avatar      : images/me_halo.jpg
  links:
    - label: "Contact"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cjmulque@buffalo.edu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://connormulqueen.tech"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/ConnorMulqueen"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@connormulqueen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/connormulqueen/"

#Defaults:
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
